### ISSUE TITLE
Reducer is not refreshed with latest data

### ISSUE THREAD

**Issue by chase439** [chrisfrank/rack-reducer#11]
In the README example (pasted below), ArtistReducer is not refreshed with latest Artist.all when a new artist is created. To reproduce the issue:

- visit index page with no parameters. Expect all artists to appear.
- create a new record
- revisit index page. Expect new record to not appear, when it should appear.

```
# app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # Step 1: Instantiate a reducer
  ArtistReducer = Rack::Reducer.new(
    Artist.all,
    ->(name:) { where('lower(name) like ?', "%#{name.downcase}%") },
    ->(genre:) { where(genre: genre) },
  )

  # Step 2: Apply the reducer to incoming requests
  def index
    @artists = ArtistReducer.apply(params)
    render json: @artists
  end
end
```

**Comment by chase439** [comment]
I ended up calling Rack::Reducer as a function
```
class ArtistsController < ApplicationController
  def index
    @artists = Rack::Reducer.call(params, dataset: Artist.all, filters: [
      ->(name:) { where('lower(name) like ?', "%#{name.downcase}%") },
      ->(genre:) { where(genre: genre) },
    ])
    render json: @artists
  end
end
```

**Comment by chrisfrank** [comment]
Thanks very much for reporting this, @chase439, and for the detailed steps to reproduce. I have a PR open that should fix the issue — do you have time to test it in your app? Making the following change in your Gemfile should let you load the patched version:

```ruby
gem 'rack-reducer', git: 'https://github.com/chrisfrank/rack-reducer.git', branch: 'bug/rails-refresh'
```

**Comment by chase439** [comment]
It works, thank you!
