### ISSUE TITLE
Handling ranges with optional parameters

### ISSUE THREAD

**Issue by Yihwan** [chrisfrank/rack-reducer#3]
Hey Chris! Any tips on how to filter with optional min/max query parameters? Optional meaning users could query one, both, or none. 

For example: 

count_min=5 -> would return all results greater than 5
count_min=5?count_max=10 -> would return all results between 5 and 10 inclusive

**Comment by Yihwan** [comment]
Nvm, figured it out! :)

**Comment by chrisfrank** [comment]
@Yihwan apologies for not seeing this when you posted it! I only recently realized I wasn't subscribed to all notifications from this repo. Glad you sorted it out — please feel free to open other issues if you run into other questions.
