### ISSUE TITLE
RFC re: proposed changes in 2.0

### ISSUE THREAD

**Issue by chrisfrank** [chrisfrank/rack-reducer#4]
I'd like to propose two API changes for 2.0, aimed at improving performance, simplifying the docs, and making it easier to integrate Rack::Reducer consistently across different Rack stacks.

1. **Unify the functional and mixin-style APIs**
2. **Drop or move the middleware API**

These changes could be mostly backward-compatible, but they'd be cleaner to implement as breaking changes. I'm eager for input before I make a decision.

## 1. Unify the functional and mixin APIs.

Rack::Reducer’s [functional style](https://github.com/chrisfrank/rack-reducer#functional-style) is verbose, and it inefficiently encourages allocating a new array of filter functions on every request. How inefficient this is depends on your setup, but from rough benchmarks it's ~10% slower and ~30% less memory efficient than the mixin style.

The [mixin style](https://github.com/chrisfrank/rack-reducer#mixin-style), on the other hand, is tightly coupled to Rails-ish models, and I don't like that it defines `reduce` on a class that in practice often returns an an Enumerable, which already has its own implementation of `reduce`.

I propose unifying the two APIs into one. It should be terse and efficient like the mixin style, and self-contained like the functional style. Here's what I have in mind:

```ruby
# Proposed unified API for 2.0
class App < SinatraLike::Base
  class Artist < SomeORM::Model
  end

  # Instantiate a "reducer" once, on app boot
  ArtistsReducer = Rack::Reducer.new(
    Artist.all,
    ->(genre:) { where(genre: genre) },
    ->(sort:) { order(sort.to_sym) },
  )

  get '/artists' do
    # Call the reducer on each request
    @artists = ArtistsReducer.call(params)
    @artists.all.to_json
  end
end

# Current 1.0 functional style, for comparison
class FunctionalStyle < SinatraLike::Base
  class Artist < SomeORM::Model
  end

  get '/artists' do
    # this allocates a new array of filters on each request :(
    @artists = Rack::Reducer.call(params, dataset: Artist.all, filters: [
      ->(genre:) { where(genre: genre) },
      ->(sort:) { order(sort.to_sym) },
    ])
    @artists.all.to_json
  end
end

# Current 1.0 mixin style, for comparison
class MixinStyle < SinatraLike::Base
  class Artist < SomeORM::Model
    extend Rack::Reducer
    reduces self.all, filters: [
      ->(genre:) { where(genre: genre) },
      ->(sort:) { order(sort.to_sym) },
    ]
  end

  get '/artists' do
    @artists = Artist.reduce(params)
    @artists.all.to_json
  end
end
```

With this unified API in place, we could either leave the 1.0 APIs intact for backward compatibility, or drop them in pursuit of simplicity and enforcing fast defaults. I would prefer to drop them, but would be happy to be convinced otherwise.

## 2. Drop or move the Middleware API
Rack mounts middleware by calling `::new(app, options)`, but I want to use `Rack::Reducer.new` for the API outlined above.

I’m tempted to drop the middleware API entirely, because I've never needed to use it in a real app. Any I time I could have used middleware, it has been more practical to call Rack::Reducer as a function.

If you've found a useful case for Rack::Reducer as middleware, I'd be open to including it in 2.0 under a slightly different API:

```ruby
# config.ru

# 1.0 (not supported in 2.0)
# use Rack::Reducer
# run MyApp

# 2.0 (proposed)
use Rack::Reducer::Middleware
run MyApp
```

Thanks in advance for your input.

**Comment by chrisfrank** [comment]
@shanecav84 if you have opinions re: these proposals, I'd love to hear them!

**Comment by shanecav84** [comment]
Cool. Will take a look today or tomorrow.

**Comment by shanecav84** [comment]
I like the new API pretty well: simpler and more performant but still flexible. I exclusively use RR with the functional style, and instantiating the reducer once on boot makes perfect sense to me. A few thoughts:

- `Artist.all` in the example would need to become something like `Artist.dataset` to avoid loading a static array as the dataset (unless that's what you want).
- I don't use the middleware at all and don't think I will. Moving it to the `Middleware` namespace makes sense. Should the project name be changed if you drop it?
- Re: deprecation of functional/mixin APIs: Maybe institute this new API in 2.x, add deprecation notices for functional/mixin APIs, then drop the deprecated APIs in 3.x (per semver). The notices might be useful to get more opinions of this new API - not sure how many users are going to see this Issue.
- Re: `reduce` for the mixin style. Maybe delegate to `Enumerable#reduce` when passed anything but a `Hash`?

**Comment by chrisfrank** [comment]
Thanks so much, Shane. These are very helpful points.

> Artist.all in the example would need to become something like Artist.dataset to avoid loading a static array as the dataset (unless that's what you want).

You're right, it should be `Artist.dataset` in Sequel, and I think`Artist.all` in ActiveRecord >= 4? I'll need to make sure the examples are correct for each framework.

> I don't use the middleware at all and don't think I will. Moving it to the Middleware namespace makes sense. Should the project name be changed if you drop it?

Huh! I guess without the middleware this gem wouldn't actually be dependent on Rack at all. Renaming it would mean maintaining two libraries instead of one, though. I'll need to think more about the tradeoffs. If it lives on as Rack::Reducer instead of becoming a new gem, then I will definitely follow your advice re: deprecating the 1.0 APIs gracefully. Thanks again!
