### ISSUE TITLE
Default filters not working when params are empty

### ISSUE THREAD

**Issue by danielpuglisi** [chrisfrank/rack-reducer#6]
Hey @chrisfrank 

First of all, thanks for this amazing gem. Started using v1.0.1 at the beginning of the year and was able to clean up a lot of index actions 👍😉

Tried v1.1.0 in a new project today and noticed a slight change in how default filters are working (or not working) due to the addition in https://github.com/chrisfrank/rack-reducer/blob/master/lib/rack/reducer/reduction.rb#L22 which causes them to be skipped when params are empty. Not sure if this is intentional. I used them for defining default ordering so far.

**Comment by chrisfrank** [comment]
Thanks very much for reporting this, @danielpuglisi. I agree this is a bug, and in fact the readme encourages using default filters the way you've been using them 😬 

I'll cut 1.1.1 with a fix ASAP. If possible, I'd like to find a way to preserve the performance boost this change brought with it, but still apply default filters when they exist. I'm open to implementation suggestions if you have them.

**Comment by chrisfrank** [comment]
Fixed in #7!
